In [3]:
import numpy as np
x = np.array([1, 2, 3])
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
y = [1, 2, 3]
print(y)
print(type(y))

[1, 2, 3]
<class 'list'>


In [5]:

%timeit [j**4 for j in range(1,9)]


819 ns ± 47.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [6]:
import numpy as np

%timeit np.arange(1,9)**4

1.99 μs ± 125 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Creating Numpy Arrays

In [12]:
import numpy as np

x = [1, 2, 3, 4, 5]

y = np.array([1, 2, 3, 4, 5])

print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [10]:
l = []

for i in range(1, 6):
    int_1 = int(input("Enter an integer: "))
    l.append(int_1)

print(np.array(l))    

[11 12 13 14 15]


In [ ]:
#2d array
ar2 = np.array([[1, 2, 3], [4, 5, 6]])
print(ar2)
print(ar2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
#3d array
ar3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(ar3)
print(ar3.ndim) 

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3


In [19]:
#multi-dimensional array
arn = np.array([1,2,3,4,5],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10
